/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EngineerRouteRouteImport } from './routes/engineer/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineerTimesheetRouteImport } from './routes/engineer/timesheet'
import { Route as AdminTimesheetsRouteImport } from './routes/admin/timesheets'
import { Route as AdminTimesheetRouteImport } from './routes/admin/timesheet'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminReviewUserIdRouteImport } from './routes/admin/review.$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerRouteRoute = EngineerRouteRouteImport.update({
  id: '/engineer',
  path: '/engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerTimesheetRoute = EngineerTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => EngineerRouteRoute,
} as any)
const AdminTimesheetsRoute = AdminTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTimesheetRoute = AdminTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewUserIdRoute = AdminReviewUserIdRouteImport.update({
  id: '/review/$userId',
  path: '/review/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/engineer': typeof EngineerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/timesheet': typeof AdminTimesheetRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/engineer/timesheet': typeof EngineerTimesheetRoute
  '/admin/review/$userId': typeof AdminReviewUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/engineer': typeof EngineerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/timesheet': typeof AdminTimesheetRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/engineer/timesheet': typeof EngineerTimesheetRoute
  '/admin/review/$userId': typeof AdminReviewUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/engineer': typeof EngineerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/timesheet': typeof AdminTimesheetRoute
  '/admin/timesheets': typeof AdminTimesheetsRoute
  '/engineer/timesheet': typeof EngineerTimesheetRoute
  '/admin/review/$userId': typeof AdminReviewUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/engineer'
    | '/login'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/projects'
    | '/admin/timesheet'
    | '/admin/timesheets'
    | '/engineer/timesheet'
    | '/admin/review/$userId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/engineer'
    | '/login'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/projects'
    | '/admin/timesheet'
    | '/admin/timesheets'
    | '/engineer/timesheet'
    | '/admin/review/$userId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/engineer'
    | '/login'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/projects'
    | '/admin/timesheet'
    | '/admin/timesheets'
    | '/engineer/timesheet'
    | '/admin/review/$userId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EngineerRouteRoute: typeof EngineerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer': {
      id: '/engineer'
      path: '/engineer'
      fullPath: '/engineer'
      preLoaderRoute: typeof EngineerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/timesheet': {
      id: '/engineer/timesheet'
      path: '/timesheet'
      fullPath: '/engineer/timesheet'
      preLoaderRoute: typeof EngineerTimesheetRouteImport
      parentRoute: typeof EngineerRouteRoute
    }
    '/admin/timesheets': {
      id: '/admin/timesheets'
      path: '/timesheets'
      fullPath: '/admin/timesheets'
      preLoaderRoute: typeof AdminTimesheetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/timesheet': {
      id: '/admin/timesheet'
      path: '/timesheet'
      fullPath: '/admin/timesheet'
      preLoaderRoute: typeof AdminTimesheetRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review/$userId': {
      id: '/admin/review/$userId'
      path: '/review/$userId'
      fullPath: '/admin/review/$userId'
      preLoaderRoute: typeof AdminReviewUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminTimesheetRoute: typeof AdminTimesheetRoute
  AdminTimesheetsRoute: typeof AdminTimesheetsRoute
  AdminReviewUserIdRoute: typeof AdminReviewUserIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminTimesheetRoute: AdminTimesheetRoute,
  AdminTimesheetsRoute: AdminTimesheetsRoute,
  AdminReviewUserIdRoute: AdminReviewUserIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EngineerRouteRouteChildren {
  EngineerTimesheetRoute: typeof EngineerTimesheetRoute
}

const EngineerRouteRouteChildren: EngineerRouteRouteChildren = {
  EngineerTimesheetRoute: EngineerTimesheetRoute,
}

const EngineerRouteRouteWithChildren = EngineerRouteRoute._addFileChildren(
  EngineerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EngineerRouteRoute: EngineerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
